### ISSUE TITLE
Database connection issue after a few hours of server operation

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/com.bitplan.vzjava#8]
When the server has run for a few hours (in the example some 10 hours) the database connection link might fail and the home page is not displayed any more:

`Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure The last packet successfully received from the server was 35.030.921 milliseconds ago. The last packet sent successfully to the server was 4 milliseconds ago. Error Code: 0 Call: SELECT ID, ENTITY_ID, PKEY, VALUE FROM Properties Query: ReadAllQuery(referenceClass=PropertiesDao sql="SELECT ID, ENTITY_ID, PKEY, VALUE FROM Properties")

uery: ReadAllQuery(referenceClass=PropertiesDao sql="SELECT ID, ENTITY_ID, PKEY, VALUE FROM Properties")
	at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:382)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:260)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
	at com.bitplan.vzjava.jpa.PropertiesManagerDao.getProperties(PropertiesManagerDao.java:80)
	at com.bitplan.vzjava.Channel.getChannels(Channel.java:73)
	at com.bitplan.vzjava.resources.HomeResource.channelPlotResponse(HomeResource.java:82)`

**Comment by WolfgangFahl** [comment]
https://itellity.wordpress.com/2013/07/18/mysql-reconnect-issues-or-the-last-packet-successfully-received-from-the-server-xx-milliseconds-ago-errors/

recommends:
```
1. add ?autoReconnect=true to you jdbc URL

jdbc:mysql://:3306/?autoReconnect=true
```

**Comment by WolfgangFahl** [comment]
The RESTFul access to e.g. http://localhost:8380/vz/dbconfig still works.
